### ISSUE TITLE
https://raw.githubusercontent.com/tjguk/kelston_mu_code/master/get_age.py

### ISSUE THREAD

**Issue by tommyp6** [tjguk/kelston_mu_code#1]
Why you need to `import sys` and I don' t understand `if yes_no.lower() ...` If lower is not defined how it works ?

**Comment by tjguk** [comment]
Good catch, @TommyPujol06! The `import sys` is leftover from a version where I used `sys.exit` to finish early if the date of birth wasn't correct.

`.lower` is defined on every string. Just try it, eg: `"Tim".lower()`

**Comment by tommyp6** [comment]
Ok thanks !
