### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by tommyp6** [tjguk/kelston_mu_code#8]
In the commit : 
https://github.com/KelstonClub/kelston_mu_code/commit/fc8cb9a742daf519105f99ec5f68991668df64df

You include the : 
```python
import os
os.chdir(r"C:\Users\tim\work-in-progress\kelston_mu_code\20190126")
```
But for every one except of you it is useless and we have to quit it. (In our computers)

**Also enable issues in the @KelstonClub fork.**

**Comment by tjguk** [comment]
... or you could all change your name to "Tim" -- that would work, too!

**Comment by tjguk** [comment]
Now enabled issues in the KelstonClub fork. Thanks for the heads-up

**Comment by tommyp6** [comment]
> ... or you could all change your name to "Tim" -- that would work, too!

Yes, but I am on Linux wich would be something like `/home/Tim/work-in-progress/...`
I also would have to create the work-in-progress folder, but all right.

**Comment by tjguk** [comment]
I wasn't serious :)

But, in fact, I'll upload a change (which I didn't want to do on Saturday to as not to complicate things) which will look for the data file relative to the code file.

**Comment by tjguk** [comment]
I've just pushed a commit against the first two files:

https://github.com/KelstonClub/kelston_mu_code/commit/1d553b9ade5ab7b623d49436feac8c9d50c29d02

to illustrate how to look for the data file relative to the code file. It's a better solution (in general) to this problem, but for a quick example it's actually more intrusive.

I'll have a discussion with the other Mu developers to see what they think we should do when we load code from a non-standard location.

**Comment by tommyp6** [comment]
Ok
